"use client";

import React, { useState, useMemo } from "react";
import { Moon, Car, TrendingUp, TrendingDown, DollarSign, Share2, Check, Calendar as CalendarIcon, History } from "lucide-react";
import { formatCurrency } from "@/lib/currency";

interface IncomeItem {
  id: string;
  amount: number;
  date: string;
  vehicleNumber?: string;
  customerName?: string;
}

interface ExpenseItem {
  id: string;
  title?: string;
  category: string;
  amount: number;
  date: string;
  notes?: string;
}

interface DailyEodSummaryProps {
  currency: string;
  stationName: string;
  allIncomes: IncomeItem[];
  allExpenses: ExpenseItem[];
  todayCarsCount: number;
  activeStaffCount: number;
}

export function DailyEodSummaryCard({
  currency,
  stationName,
  allIncomes,
  allExpenses,
  todayCarsCount,
  activeStaffCount,
}: DailyEodSummaryProps) {
  const [copied, setCopied] = useState(false);
  const [selectedDateStr, setSelectedDateStr] = useState<string>(
    new Date().toISOString().split("T")[0]
  );

  // Helper to normalize Date string comparison (YYYY-MM-DD)
  const getFormattedDateString = (d: Date) => {
    return d.toISOString().split("T")[0];
  };

  const todayIsoStr = useMemo(() => {
    try {
      return new Date().toISOString().split("T")[0];
    } catch {
      return "";
    }
  }, []);

  // Filter incomes & expenses for selected date
  const { dayIncomes, dayExpenses, dayRevenue, dayExpensesTotal, dayNetProfit } = useMemo(() => {
    const targetDateStr = selectedDateStr;

    const filteredIncomes = (allIncomes || []).filter((inc) => {
      if (!inc || !inc.date) return false;
      try {
        const d = new Date(inc.date);
        if (isNaN(d.getTime())) return false;
        return d.toISOString().split("T")[0] === targetDateStr;
      } catch {
        return false;
      }
    });

    const filteredExpenses = (allExpenses || []).filter((exp) => {
      if (!exp || !exp.date) return false;
      try {
        const d = new Date(exp.date);
        if (isNaN(d.getTime())) return false;
        return d.toISOString().split("T")[0] === targetDateStr;
      } catch {
        return false;
      }
    });

    const rev = filteredIncomes.reduce((sum, i) => sum + Number(i.amount || 0), 0);
    const expTotal = filteredExpenses.reduce((sum, e) => sum + Number(e.amount || 0), 0);

    return {
      dayIncomes: filteredIncomes,
      dayExpenses: filteredExpenses,
      dayRevenue: rev,
      dayExpensesTotal: expTotal,
      dayNetProfit: rev - expTotal,
    };
  }, [selectedDateStr, allIncomes, allExpenses]);

  // Cars count for selected date
  const selectedCarsCount = useMemo(() => {
    if (selectedDateStr === todayIsoStr) {
      return todayCarsCount;
    }
    return dayIncomes.length;
  }, [selectedDateStr, todayIsoStr, todayCarsCount, dayIncomes]);

  const displayDateText = useMemo(() => {
    const [y, m, d] = selectedDateStr.split("-").map(Number);
    const dateObj = new Date(y, m - 1, d);
    return dateObj.toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  }, [selectedDateStr]);

  const isTodaySelected = selectedDateStr === todayIsoStr;

  // Quick Preset Date Handlers
  const handleSetQuickDate = (offsetDays: number) => {
    const d = new Date();
    d.setDate(d.getDate() - offsetDays);
    setSelectedDateStr(d.toISOString().split("T")[0]);
  };

  // Generate clean WhatsApp / Text briefing snippet for Store Owners
  const handleCopySummary = () => {
    const summaryText = `🌙 *${stationName} — EOD Summary Report*
📅 Date: ${displayDateText} ${isTodaySelected ? "(Today)" : "(Historical Record)"}

🚗 *Cars Washed:* ${selectedCarsCount}
💰 *Gross Revenue:* ${formatCurrency(dayRevenue)}
💸 *Operational Expenses:* ${formatCurrency(dayExpensesTotal)}
📈 *Net Daily Profit:* ${formatCurrency(dayNetProfit)}
👥 *Staff On Shift:* ${activeStaffCount}

${dayExpenses.length > 0 ? `*Expense Breakdown:*
${dayExpenses.map((e) => `• ${e.category}: ${formatCurrency(e.amount)} (${e.title || e.notes || "General"})`).join("\n")}` : "• No expenses logged for this date."}

Generated by WashDeck Operations.`;

    navigator.clipboard.writeText(summaryText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="bg-white text-slate-900 border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
      {/* Header Bar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600 shrink-0">
            <Moon size={20} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base font-bold text-slate-900 tracking-tight">
                Nightly EOD Summary & History
              </h2>
              <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold border ${
                isTodaySelected
                  ? "bg-blue-50 text-blue-700 border-blue-200"
                  : "bg-slate-100 text-slate-700 border-slate-200"
              }`}>
                {isTodaySelected ? "Today's Live Report" : "Historical Summary"}
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-0.5">{displayDateText}</p>
          </div>
        </div>

        {/* Date Selector & Action Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          {/* Quick Date Pills */}
          <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-xl border border-slate-200">
            <button
              type="button"
              onClick={() => handleSetQuickDate(0)}
              className={`px-2.5 py-1 rounded-lg text-xs font-bold transition ${
                isTodaySelected
                  ? "bg-blue-600 text-white shadow-xs"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              Today
            </button>
            <button
              type="button"
              onClick={() => handleSetQuickDate(1)}
              className={`px-2.5 py-1 rounded-lg text-xs font-bold transition ${
                selectedDateStr === new Date(Date.now() - 86400000).toISOString().split("T")[0]
                  ? "bg-blue-600 text-white shadow-xs"
                  : "text-slate-600 hover:text-slate-900"
              }`}
            >
              Yesterday
            </button>
            <button
              type="button"
              onClick={() => handleSetQuickDate(3)}
              className="px-2.5 py-1 rounded-lg text-xs font-semibold text-slate-600 hover:text-slate-900 transition hidden sm:inline-block"
            >
              3 Days Ago
            </button>
          </div>

          {/* Custom Date Picker */}
          <div className="relative flex items-center">
            <input
              type="date"
              value={selectedDateStr}
              max={todayIsoStr}
              onChange={(e) => e.target.value && setSelectedDateStr(e.target.value)}
              className="h-9 px-3 bg-white border border-slate-200 text-slate-800 text-xs font-semibold rounded-xl outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-600 transition cursor-pointer"
            />
          </div>

          <button
            onClick={handleCopySummary}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-slate-100 hover:bg-slate-200 active:scale-95 text-slate-800 rounded-xl text-xs font-bold border border-slate-200 transition shadow-xs"
          >
            {copied ? <Check size={14} className="text-blue-600" /> : <Share2 size={14} />}
            <span>{copied ? "Copied Report!" : "Share / Copy"}</span>
          </button>
        </div>
      </div>

      {/* Grid Metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {/* Cars Processed */}
        <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-[10px] font-bold uppercase tracking-wider">Cars Serviced</span>
            <Car size={15} className="text-blue-600" />
          </div>
          <p className="text-xl font-bold text-slate-900 mt-1">{selectedCarsCount}</p>
          <p className="text-[10px] text-slate-500 mt-0.5">Vehicles washed on date</p>
        </div>

        {/* Daily Revenue */}
        <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-[10px] font-bold uppercase tracking-wider">Gross Revenue</span>
            <TrendingUp size={15} className="text-blue-600" />
          </div>
          <p className="text-xl font-bold text-slate-900 mt-1">
            {formatCurrency(dayRevenue)}
          </p>
          <p className="text-[10px] text-slate-500 mt-0.5">Total inflow on date</p>
        </div>

        {/* Daily Expenses */}
        <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
          <div className="flex items-center justify-between text-slate-500">
            <span className="text-[10px] font-bold uppercase tracking-wider">Total Expenses</span>
            <TrendingDown size={15} className="text-slate-400" />
          </div>
          <p className="text-xl font-bold text-slate-900 mt-1">
            {formatCurrency(dayExpensesTotal)}
          </p>
          <p className="text-[10px] text-slate-500 mt-0.5">{dayExpenses.length} expenses logged</p>
        </div>

        {/* Net Profit */}
        <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
          <div className="flex items-center justify-between text-slate-600">
            <span className="text-[10px] font-bold uppercase tracking-wider">Net Profit</span>
            <DollarSign size={15} className="text-blue-600" />
          </div>
          <p className="text-xl font-bold text-slate-900 mt-1">
            {formatCurrency(dayNetProfit)}
          </p>
          <p className="text-[10px] text-slate-500 mt-0.5">Revenue minus expenses</p>
        </div>
      </div>

      {/* Expense Detail Breakdown for Selected Date */}
      {dayExpenses.length > 0 ? (
        <div className="pt-3 border-t border-slate-100">
          <p className="text-[11px] font-bold uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1.5">
            <History size={13} className="text-blue-600" />
            <span>Itemized Expenses for {displayDateText}</span>
          </p>
          <div className="space-y-1.5 max-h-36 overflow-y-auto pr-1">
            {dayExpenses.map((expense) => (
              <div
                key={expense.id}
                className="flex items-center justify-between p-2 rounded-xl bg-slate-50 text-xs border border-slate-200/80"
              >
                <div>
                  <span className="font-bold text-slate-800">{expense.category}</span>
                  {(expense.title || expense.notes) && (
                    <span className="text-slate-500 text-[11px] ml-2">({expense.title || expense.notes})</span>
                  )}
                </div>
                <span className="font-bold text-slate-800">{formatCurrency(expense.amount)}</span>
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="pt-2 border-t border-slate-100 text-[11px] text-slate-500 font-medium">
          No expenses recorded for {displayDateText}.
        </div>
      )}
    </div>
  );
}
