"use client";

import React, { useState } from "react";
import { Moon, Car, TrendingUp, TrendingDown, DollarSign, Users, Share2, Check, Clock } from "lucide-react";
import { formatCurrency } from "@/lib/currency";

interface ExpenseItem {
  id: string;
  category: string;
  amount: number;
  description: string | null;
}

interface DailyEodSummaryProps {
  currency: string;
  stationName: string;
  todayCarsCount: number;
  todayRevenue: number;
  todayExpenses: number;
  todayExpensesList: ExpenseItem[];
  activeStaffCount: number;
}

export function DailyEodSummaryCard({
  currency,
  stationName,
  todayCarsCount,
  todayRevenue,
  todayExpenses,
  todayExpensesList,
  activeStaffCount,
}: DailyEodSummaryProps) {
  const [copied, setCopied] = useState(false);
  const netProfit = todayRevenue - todayExpenses;
  const todayDateStr = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  // Generate clean WhatsApp / Text briefing snippet for Store Owners
  const handleCopySummary = () => {
    const summaryText = `🌙 *${stationName} — Daily EOD Summary (10:00 PM)*
📅 Date: ${todayDateStr}

🚗 *Cars Washed Today:* ${todayCarsCount}
💰 *Gross Revenue Today:* ${formatCurrency(todayRevenue)}
💸 *Daily Operational Expenses:* ${formatCurrency(todayExpenses)}
📈 *Net Daily Profit:* ${formatCurrency(netProfit)}
👥 *Staff On Shift Today:* ${activeStaffCount}

${todayExpensesList.length > 0 ? `*Today's Expense Breakdown:*
${todayExpensesList.map((e) => `• ${e.category}: ${formatCurrency(e.amount)} (${e.description || "General"})`).join("\n")}` : "• No expenses logged today."}

Generated by WashDeck Operations.`;

    navigator.clipboard.writeText(summaryText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="bg-slate-900 text-white border border-slate-800 rounded-2xl p-5 shadow-xl space-y-4">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-blue-600/20 border border-blue-500/30 flex items-center justify-center text-blue-400 shrink-0">
            <Moon size={20} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base font-extrabold text-white tracking-tight">
                Nightly EOD Summary (10:00 PM)
              </h2>
              <span className="px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20 text-[10px] font-bold">
                Daily Report
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">{todayDateStr}</p>
          </div>
        </div>

        <button
          onClick={handleCopySummary}
          className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-slate-800 hover:bg-slate-700 active:scale-95 text-white rounded-xl text-xs font-bold border border-slate-700 transition shadow-sm self-start sm:self-auto shrink-0"
        >
          {copied ? <Check size={14} className="text-emerald-400" /> : <Share2 size={14} />}
          <span>{copied ? "Copied Briefing!" : "Share / Copy EOD Report"}</span>
        </button>
      </div>

      {/* Grid Metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {/* Cars Processed */}
        <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700/60">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-black uppercase tracking-wider">Cars Today</span>
            <Car size={15} className="text-blue-400" />
          </div>
          <p className="text-xl font-black text-white mt-1">{todayCarsCount}</p>
          <p className="text-[10px] text-slate-400 mt-0.5">Vehicles serviced today</p>
        </div>

        {/* Today's Revenue */}
        <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700/60">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-black uppercase tracking-wider">Daily Revenue</span>
            <TrendingUp size={15} className="text-emerald-400" />
          </div>
          <p className="text-xl font-black text-emerald-400 mt-1">
            {formatCurrency(todayRevenue)}
          </p>
          <p className="text-[10px] text-slate-400 mt-0.5">Gross inflow today</p>
        </div>

        {/* Daily Expenses */}
        <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700/60">
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-black uppercase tracking-wider">Daily Expenses</span>
            <TrendingDown size={15} className="text-rose-400" />
          </div>
          <p className="text-xl font-black text-rose-400 mt-1">
            {formatCurrency(todayExpenses)}
          </p>
          <p className="text-[10px] text-slate-400 mt-0.5">{todayExpensesList.length} expenses logged</p>
        </div>

        {/* Net Daily Profit */}
        <div className={`p-3.5 rounded-xl border ${netProfit >= 0 ? "bg-emerald-950/40 border-emerald-800/50" : "bg-rose-950/40 border-rose-800/50"}`}>
          <div className="flex items-center justify-between text-slate-400">
            <span className="text-[10px] font-black uppercase tracking-wider">Net Profit</span>
            <DollarSign size={15} className={netProfit >= 0 ? "text-emerald-400" : "text-rose-400"} />
          </div>
          <p className={`text-xl font-black mt-1 ${netProfit >= 0 ? "text-emerald-400" : "text-rose-400"}`}>
            {formatCurrency(netProfit)}
          </p>
          <p className="text-[10px] text-slate-400 mt-0.5">Revenue minus expenses</p>
        </div>
      </div>

      {/* Expense Detail Breakdown (if any logged today) */}
      {todayExpensesList.length > 0 && (
        <div className="pt-2 border-t border-slate-800">
          <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-2">
            Today's Itemized Expenses
          </p>
          <div className="space-y-1.5 max-h-36 overflow-y-auto pr-1">
            {todayExpensesList.map((expense) => (
              <div
                key={expense.id}
                className="flex items-center justify-between p-2 rounded-lg bg-slate-800/50 text-xs border border-slate-700/40"
              >
                <div>
                  <span className="font-bold text-slate-200">{expense.category}</span>
                  {expense.description && (
                    <span className="text-slate-400 text-[11px] ml-2">({expense.description})</span>
                  )}
                </div>
                <span className="font-bold text-rose-400">{formatCurrency(expense.amount)}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
