import { CreditCard, CheckCircle2, Clock, AlertCircle, Upload, FileText, ArrowRight } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { formatCurrency, formatDate } from "@/lib/currency";
import { StatusBadge, PlanBadge } from "@/components/ui/badge";

export default async function PaymentsPage() {
  await requireRole(["SUPER_ADMIN"]);

  let subscriptions: any[] = [];
  try {
    subscriptions = await prisma.stationSubscription.findMany({
      orderBy: { startDate: "desc" },
      take: 30,
      include: {
        station: { select: { name: true, slug: true, status: true } },
        subscription: { select: { name: true, price: true } },
      },
    });
  } catch (err) {
    subscriptions = [
      {
        id: "sub-1",
        status: "ACTIVE",
        startDate: new Date(),
        endDate: new Date(Date.now() + 90 * 86400000),
        station: { name: "Apex Luxury Detailing", slug: "apex-riyadh", status: "ACTIVE" },
        subscription: { name: "Enterprise Pro", price: 299 },
      },
      {
        id: "sub-2",
        status: "ACTIVE",
        startDate: new Date(),
        endDate: new Date(Date.now() + 60 * 86400000),
        station: { name: "WashDeck Express", slug: "washdeck-kochi", status: "ACTIVE" },
        subscription: { name: "Starter", price: 149 },
      },
    ];
  }

  return (
    <div className="px-4 sm:px-6 py-6 space-y-6 max-w-6xl mx-auto">
      <div>
        <h1 className="text-xl font-extrabold text-slate-900 tracking-tight">
          Manual Payment Workflow & Verification
        </h1>
        <p className="text-xs text-slate-400 font-medium mt-0.5">
          Verify offline/bank/UPI transfer proofs and activate subscription lifecycles.
        </p>
      </div>

      {/* ── 7-Step Workflow Explanation Banner ─────────────────────── */}
      <div className="bg-gradient-to-r from-wd-teal-900 to-slate-900 rounded-2xl p-6 text-white shadow-md">
        <h2 className="text-sm font-bold uppercase tracking-wider text-wd-teal-300">
          SaaS Billing Lifecycle Flow
        </h2>
        <p className="text-xs text-slate-300 mt-1 max-w-2xl leading-relaxed">
          When stations pay via bank transfer or UPI, their payments follow a structured 7-step verification pipeline before automatic license activation.
        </p>

        <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2 mt-5 text-center">
          {[
            { step: "1", title: "Draft Invoice", sub: "Generated by Admin" },
            { step: "2", title: "Invoice Sent", sub: "Email & Dashboard" },
            { step: "3", title: "Awaiting Pay", sub: "Station transfers" },
            { step: "4", title: "Proof Upload", sub: "Screenshot / UTR" },
            { step: "5", title: "Verification", sub: "Admin reviews bank" },
            { step: "6", title: "Approved", sub: "License activated" },
            { step: "7", title: "Receipt", sub: "PDF sent automatically" },
          ].map((item, idx) => (
            <div
              key={idx}
              className="bg-white/10 backdrop-blur-xs rounded-xl p-2.5 border border-white/10 flex flex-col justify-between"
            >
              <span className="text-[10px] font-black text-wd-teal-300 uppercase tracking-widest">
                Stage {item.step}
              </span>
              <p className="text-xs font-bold mt-1 text-white leading-tight">{item.title}</p>
              <p className="text-[9px] text-slate-300 mt-0.5">{item.sub}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Billing Records Table ────────────────────────────────── */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <div className="p-5 border-b border-slate-100 flex items-center justify-between">
          <h2 className="text-sm font-bold text-slate-900">Recent Subscription Billing Transactions</h2>
          <span className="text-xs text-slate-400 font-semibold">{subscriptions.length} records</span>
        </div>

        {subscriptions.length === 0 ? (
          <p className="text-xs text-slate-400 py-12 text-center">No subscription billing records found.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-slate-100 bg-slate-50/60 font-bold text-[10px] text-slate-400 uppercase tracking-wider">
                  <th className="py-3 px-4">Customer Station</th>
                  <th className="py-3 px-4">Plan Package</th>
                  <th className="py-3 px-4">Amount</th>
                  <th className="py-3 px-4">Period</th>
                  <th className="py-3 px-4">Billing Status</th>
                  <th className="py-3 px-4 text-right">Verification Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {subscriptions.map((sub) => (
                  <tr key={sub.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="py-3 px-4">
                      <p className="font-bold text-slate-800">{sub.station.name}</p>
                      <p className="text-[10px] text-slate-400">@{sub.station.slug}</p>
                    </td>
                    <td className="py-3 px-4">
                      <PlanBadge plan={sub.subscription.name} size="xs" />
                    </td>
                    <td className="py-3 px-4 font-extrabold text-slate-800">
                      {formatCurrency(Number(sub.subscription.price), "INR")}
                    </td>
                    <td className="py-3 px-4 text-slate-500">
                      {formatDate(sub.startDate)} → {formatDate(sub.endDate)}
                    </td>
                    <td className="py-3 px-4">
                      <StatusBadge status={sub.status} size="xs" />
                    </td>
                    <td className="py-3 px-4 text-right">
                      <span className="text-[11px] font-bold text-wd-teal-700 hover:underline cursor-pointer">
                        {sub.status === "ACTIVE" ? "View Receipt" : "Verify Payment"}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
